# Generated by Django 2.2.10 on 2021-07-04 17:30

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('full_name', models.CharField(max_length=400, null=True, verbose_name='Пользователь')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Cтатус персонала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждён?')),
                ('verification_uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Уникальный UUID проверки')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-is_active', '-is_verified', '-full_name'],
            },
            managers=[
                ('objects', users.models.UserAccountManager()),
            ],
        ),
    ]
