# Generated by Django 2.2.10 on 2021-07-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название опроса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Дата старта')),
                ('stop', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('interrogation_self', models.ForeignKey(default=0, on_delete='CASCADE', to='interrogation.Interrogation', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('type', models.CharField(choices=[('Text', 'Ответ текстом'), ('One option', 'Ответ с выбором одного варианта'), ('Several options', 'Ответ с выбором нескольких вариантов')], default='Text', max_length=200, verbose_name='Тип опроса')),
                ('interrogation', models.ForeignKey(default=0, on_delete='CASCADE', to='interrogation.Interrogation', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-type'],
            },
        ),
    ]
