# Generated by Django 2.2.10 on 2021-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interrogation', '0002_auto_20210702_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrogation',
            name='questions',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete='CASCADE', related_name='question', to='interrogation.Interrogation', verbose_name='Вопрос'),
        ),
    ]
