# Generated by Django 2.2.10 on 2021-07-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interrogation', '0003_auto_20210702_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrogation',
            name='questions',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete='CASCADE', related_name='questions', to='interrogation.Question', verbose_name='Вопрос'),
        ),
    ]
