# Generated by Django 2.2.10 on 2021-07-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interrogation', '0007_auto_20210703_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrogation',
            name='stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
