# Generated by Django 2.2.10 on 2021-07-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interrogation', '0009_auto_20210703_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='interrogation',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='interrogation.Interrogation'),
            preserve_default=False,
        ),
    ]
