# Generated by Django 2.2.10 on 2021-07-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interrogation', '0010_answer_interrogation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='lock_other',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='points',
        ),
    ]
